Armen egiian/cu 861mayzhq/create basic cru ds
Araati/aggregator pull request #1
Opened 2023-02-05 15:46 UTC by Nervikus

2023-02-05 15:46 UTC, Araati commented
Task linked: [CU-861mayzhq Create basic CRUDs](https://app.clickup.com/t/861mayzhq)

2023-02-05 16:40 UTC, Araati requested changes

2023-02-05 16:40 UTC, Araati commented on src/main/java/com/ourcompany/aggregator/controller/TagController.java
> +                          @PathVariable final long id) {
Я не прошу тебя исправлять, просто обращаю внимание: у тебя во всех контроллерах размер отступа (второй аргумент в методе update) разный, что режет глаз.

2023-02-05 16:40 UTC, Araati commented on src/main/java/com/ourcompany/aggregator/controller/TagController.java
> +    public List<Tag> findAll() {
В контроллере проектов getAll(), а здесь findAll()

2023-02-05 16:40 UTC, Araati commented on src/main/java/com/ourcompany/aggregator/dto/PositionCreateDTO.java
> +public class PositionCreateDTO {
Помнишь, что ты в каждом контроллере писал @ Valid? Это нужно для работы аннотаций валидации в дто (их сейчас нет). Сейчас в наше дто могут закрасться нули (ибо пользователь может вообще отправить пустой json, или json с пустыми строками). Это просто информация к твоему сведению, плюс я создал по этому поводу таску #861mb2yug , в которой мы эти моменты исправим

2023-02-05 16:40 UTC, Araati commented on src/main/java/com/ourcompany/aggregator/dto/PositionUpdateDTO.java
> +
В позиции, помимо position, есть поле skills, которое тоже должно быть изменяемым

2023-02-05 16:40 UTC, Araati commented on src/main/java/com/ourcompany/aggregator/dto/ProjectCreateDTO.java
> +    @JsonProperty(value = "tags")
Возможно всё же лучше написать tagList в аннотации, либо переименовать переменную везде в "tags", чтобы не было расхождений

2023-02-05 16:40 UTC, Araati commented on src/main/java/com/ourcompany/aggregator/dto/TagUpdateDTO.java
> +    private String label;
Нету обновления String type. Тут придется переписывать логику ДТО и сервиса по аналогии с проектами

2023-02-05 16:40 UTC, Araati commented on src/main/java/com/ourcompany/aggregator/model/entity/TagEntity.java
> +    @Column(name = "updated_at")
Забыл nullable = false

2023-02-05 16:40 UTC, Araati commented on src/main/java/com/ourcompany/aggregator/service/PositionService.java
> +                .withPosition(request.getPosition());
.withSkills(request.getSkills().orElse(entity.getSkills())

2023-02-05 16:40 UTC, Araati commented on src/main/java/com/ourcompany/aggregator/service/PositionService.java
> +        //В случае добавление новых полей в position необходимо расширить код ниже
Удали этот комментарий

2023-02-05 16:40 UTC, Araati commented on src/main/java/com/ourcompany/aggregator/service/ProjectService.java
>          //В случае добавление новых полей в Project необходимо расширить код ниже
Удали этот комментарий

2023-02-05 16:40 UTC, Araati commented on src/main/java/com/ourcompany/aggregator/service/TagService.java
> +                .withLabel(request.getLabel());
и .withType(request.getType().orElse(entity.getType())

2023-02-05 16:40 UTC, Araati commented on src/main/java/com/ourcompany/aggregator/service/TagService.java
> +        //В случае добавление новых полей в tag необходимо расширить код ниже
Удали этот комментарий

2023-02-06 10:50 UTC, Nervikus commented on src/main/java/com/ourcompany/aggregator/controller/TagController.java
> +                          @PathVariable final long id) {
Я их копировал с контроллера проекта, который ты делал)) но всё равно исправлю)

2023-02-06 10:56 UTC, Nervikus commented on src/main/java/com/ourcompany/aggregator/controller/TagController.java
> +    public List<Tag> findAll() {
Везде заменил на findAll()

2023-02-06 11:01 UTC, Nervikus commented on src/main/java/com/ourcompany/aggregator/dto/PositionUpdateDTO.java
> +
Сделал

2023-02-06 11:09 UTC, Nervikus commented on src/main/java/com/ourcompany/aggregator/dto/PositionCreateDTO.java
> +public class PositionCreateDTO {
Сделал и таску закрыл. Можешь проверять

2023-02-06 11:13 UTC, Nervikus commented on src/main/java/com/ourcompany/aggregator/dto/ProjectCreateDTO.java
> +    @JsonProperty(value = "tags")
Исправил в аннотациях на tag_list

2023-02-06 11:14 UTC, Nervikus commented on src/main/java/com/ourcompany/aggregator/service/PositionService.java
> +                .withPosition(request.getPosition());
Готово

2023-02-06 11:21 UTC, Nervikus commented on src/main/java/com/ourcompany/aggregator/service/PositionService.java
> +        //В случае добавление новых полей в position необходимо расширить код ниже
Готово

2023-02-06 11:21 UTC, Nervikus commented on src/main/java/com/ourcompany/aggregator/service/ProjectService.java
>          //В случае добавление новых полей в Project необходимо расширить код ниже
Готово

2023-02-06 11:22 UTC, Nervikus commented on src/main/java/com/ourcompany/aggregator/service/TagService.java
> +        //В случае добавление новых полей в tag необходимо расширить код ниже
Готово

2023-02-06 11:26 UTC, merged